OCTRI/ember-i18next

app/helpers/t.js, tests/acceptance/injections-test.js, tests/acceptance/translation-test.js, tests/helpers/safe-reset.js
The `this` pointer in HTMLBars helpers is set to `undefined` by Ember 1.11. This PR changes the way the `t` utility is looked up in the container to find the container via the current view, which is compatible with Ember 1.10 and Ember 1.11. This fixes #5.
=> Make HTMLBars Helper Compatible With Ember 1.11

app/services/i18n.js, tests/acceptance/service-init-actions-test.js, tests/acceptance/service-locale-change-actions-test.js, tests/dummy/app/router.js, tests/dummy/app/routes/test-init.js, tests/unit/services/i18n-test.js
Allow registration of actions to execute before i18next functions that destroy library state are called. Makes it possible to cache and restore or re-fetch resources when the library is initialized or the locale changes.
=> Pre- and post-init functions

app/services/i18n.js, tests/acceptance/mixin-test.js, tests/acceptance/service-locale-change-actions-test.js, tests/acceptance/translation-test.js, tests/dummy/app/routes/index.js, tests/dummy/app/templates/index.hbs, tests/dummy/config/environment.js
Refactor promises handled during initialization and setting the locale to use an explicit chain of promises rather than `Ember.RSVP.all` to prevent a race condition that occurred with setting the locale.
The refactor above highlighted some issues with the way state is set up in the acceptance tests. The tests were previously implicitly expecting the application to be in a certain state and would fail if they ran in some orders. With this patch, the tests now ensure the application is in the stat they expect before making any assertions.
=> Init promise refactor

README.md, app/services/i18n.js, tests/acceptance/service-init-actions-test.js, tests/acceptance/service-locale-change-actions-test.js
It would be interesting to have access to the new locale when running pre-init actions, and the old local when running post-init actions. So actions can be executed according to this locale value.
The new locale is passed as a parameter to pre-init actions and the old one to post-init actions. Old or new locale is `undefined` when the i18n service's `initLibraryAsync` method is called.
=> Passing (old|new) locale to (pre|post)-init actions

blueprints/ember-i18next/index.js, bower.json
Add a version string to the call to `addBowerpackageToProject` to ensure i18next 2.x is not installed. Should fix #25.
=> Specify i18next version

README.md, app/services/i18n.js, blueprints/ember-i18next/index.js, bower.json, index.js, tests/dummy/config/environment.js, tests/dummy/public/locales/main/en.json, tests/dummy/public/locales/main/th.json
ember-i18next was using v1.7, this brings it up to v3.3.
Also changes service API to match the new i18next v3 API.
* The i18next API has changed so this PR will introduce breaking changes, a major version bump is required.
* i18next has introduced a plugin architecture via the ``use()`` API.  This PR doesn't completely address this.  It assumes that ember apps will be loading their catalogs via XHR and  brings in the ``i18next-xhr-backend`` by default.  Going forward it would be nice to have a way to control what plugins are loaded.
=> Bump i18next version to v3 and update api.

app/helpers/t.js, tests/acceptance/translation-test.js, tests/dummy/app/templates/index.hbs, tests/dummy/public/locales/main/en.json, tests/dummy/public/locales/main/th.json
Allow the `{{t}}` helper to render markup included in I18N keys by returning a safe string. i18next will still escape substitutions unless escaping is specifically disabled.
=> Allow Markup in I18N Keys

README.md
was pointing to http://i18next.com/pages/doc_init.html
=> fix broken link to i18next initialization options

README.md, app/helpers/t.js, app/mixins/i18n.js, app/services/i18n.js, tests/acceptance/mixin-test.js, tests/acceptance/service-locale-change-actions-test.js, tests/acceptance/translation-test.js, tests/dummy/app/app.js, tests/dummy/app/router.js, tests/dummy/app/routes/index.js, tests/dummy/app/routes/test-init.js, tests/helpers/resolver.js, tests/helpers/start-app.js, tests/unit/mixins/i18n-test.js, tests/unit/services/i18n-test.js
Fixes #29.
* use `let` and `const` instead of `var`
* use arrow functions (esp. in promise chains)
* use shorter object literal syntax for methods
=> Convert to ES2015

app/helpers/t.js
Update the `t` helper so it does not `shift` the first argument off of the `params` argument. Ember 2.9 seals this array so it cannot be modified, so the call to `shift` causes an exception. Simply extract the first argument (the translation key) using array access.
Fixes #40.
=> Don't Modify Helper Arguments

app/helpers/t.js
Hello,
When we use i18next's option `returnObjects` with `t` helper, it return a HTML safe string.
We should test `hash.returnObjects`and return a string or the result of `i18n.t` function according to the value of this option.
=> Manage i18next's option "returnObjects" in helper

app/services/i18n.js, index.js, package.json, vendor/shims/i18next-xhr-backend.js, vendor/shims/i18next.js, yarn.lock
First step of #39 and updating to the new module API. Eliminate dependency on ember-browserify by shimming i18next and i18next-xhr-backend and adding them to the vendor tree ourselves.
Largely based on examples here:
https://simplabs.com/blog/2017/02/13/npm-libs-in-ember-cli.html
=> Eliminate Browserify

.travis.yml, config/ember-try.js, testem-travis.js
* Update ember-try config format to distinguish npm and bower packages (fixes tests of release and 2.18 LTS)
* Use headless Chrome to run tests (fixes tests for beta and canary)
* Separate testem config for Travis
=> Fix Travis Tests

.eslintrc.js, .travis.yml, package-lock.json, package.json, tests/dummy/config/targets.js, yarn.lock
Update to Ember 3.0.4 and use `npm audit` to resolve vulnerable dependencies.
Configured Travis tests to run with Node 6:
* Updating testem introduced a version of execa that is incompatible with Node 4, causing tests to error out
* Node 4 LTS reached end of life in April
* Node 6 is required by Ember > 3.2, which I'm upgrading to in a forthcoming PR
=> EMBR-38 Update Dependencies

package-lock.json, package.json
Upgrade to the latest i18next and i18next-xhr-backend releases.
A [bug about plural rule for JSON compatibility v2 was introduced in 11.3.3](https://github.com/i18next/i18next/issues/1069) and [fixed in 13.1.4](https://github.com/i18next/i18next/commit/d4d329fd7042f932eedf8bba1d92234707efd04c#diff-e171f9b8b4e0f5df027bd8bd7b962f1bR1140).
=> Upgrade i18next

.travis.yml
Update the version of Node used by Travis, since Node 6 is end of life and recent Ember releases only support Node 8.x and higher.
=> Update Version of Node Used by Travis

.dependabot/config.yml
Configure Dependabot to automatically merge patch version updates for production dependencies and minor version development dependencies to match other repositories.
=> Configure Dependabot Merging

.github/workflows/test.yml
Disable the daily scheduled CI run, which is currently failing most days without appearing to ever start. It is also starting an unexpected number of jobs ([see this run for example](https://github.com/OCTRI/ember-i18next/actions/runs/78923978), which started 27 jobs instead of the expected 9). Tests still run on branch pushes and pull requests.
=> Disable Scheduled CI Run

.npmignore
Update `.npmignore` file to exclude GitHub Actions and Dependabot configuration from the npm package.
=> Exclude CI and Dependabot Config From Package

addon/helpers/t.js
Import `htmlSafe` from `@ember/template` instead of `@ember/string`. Fixes #518.
=> Import `htmlSafe` from `@ember/template`
